from models.email_output import EmailOutput
from pipelines.gmail_integration import GmailTool
from openai import OpenAI
from services.notion_service import add_email_to_notion

client = OpenAI()
# Your background and priorities information
personal_info = """
Luuk Alleman is an AI engineer and entrepreneur running his own company, Everyman AI. 
He focuses on client projects, content creation, product development, and networking. 
Luuk values efficiency and prefers concise, direct communication. He is open to scheduling meetings, 
especially those related to new business opportunities, product development, or content creation.
"""

def process_email():
    gmail_tool = GmailTool()
    email_data = gmail_tool.run()
    print(email_data)
    for email in email_data:
        # Generate subject, drafted answer, and labels using the LLM
        completion = client.beta.chat.completions.parse(
            model="gpt-4o-2024-08-06",
            messages=[
                {"role": "system", "content": f"""You are my assistant, this is who i am {personal_info}. Classify the email, generate appropriate labels, and provide a drafted response. 
                The labels should be chosen from: 
                'Client Projects', 'Team Meetings', 'Deadlines', 'Product Development', 
                'Networking', 'Personal Projects', 'Health & Wellness', 'Family & Friends', 
                'New Business', 'Invitations', 'Learning & Development', 'Financial', 
                'Legal', 'Miscellaneous', 'General Communication', 'Follow-Up'."""},
                {"role": "user", "content": f"Email received: {email['snippet']}. Please generate a subject, labels, drafted answer, and priority for this email."}
            ],
            response_format=EmailOutput,
        )

        generated_email = completion.choices[0].message.parsed
        # Create EmailOutput object with generated data
        email_output = EmailOutput(
            subject=generated_email.subject,
            original_email=email["snippet"],
            sender=email["from_address"],
            received_date=email['date'],  # Directly use the actual received date from the email
            labels=generated_email.labels,  # Use labels generated by OpenAI
            drafted_answer=generated_email.drafted_answer,
            priority=generated_email.priority
        )
        add_email_to_notion(email_output)